#  DOESN'T WORK
# FROM python:3.10

# WORKDIR /app

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     curl \
#     software-properties-common \
#     && rm -rf /var/lib/apt/lists/*

# COPY datasets ./datasets
# COPY data ./data
# COPY search ./search
# COPY requirements.txt .
# COPY main.py .

# RUN pip install --upgrade -r requirements.txt

# ENTRYPOINT [ "python", "--version"]